[project]
name = "kokoro-serve"
version = "0.1.0"
description = "Kokoro Server for TTS API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.3",
    "kokoro>=0.9.4",
    "pip>=25.3",
    "pydantic>=2.12.4",
    "soundfile>=0.13.1",
    "uvicorn>=0.38.0",
]
